# File automatically-generated by STM32CubeMX - Do not modify
#-----------------------Build Secure Project-----------------------#
add_subdirectory(Secure)

add_library(Secure_Nsclib OBJECT IMPORTED)
set_target_properties(Secure_Nsclib PROPERTIES IMPORTED_OBJECTS "${CMAKE_SOURCE_DIR}/Secure_nsclib/secure_nsclib.o")
add_dependencies(Secure_Nsclib l552-TZ_S)
#-----------------------Build NonSecure Project-----------------------#
add_subdirectory(NonSecure)

add_dependencies(l552-TZ_NS Secure_Nsclib)