# File automatically-generated by STM32CubeMX - Do not modify

# Add project symbols (macros)
target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE 
	USE_HAL_DRIVER 
	STM32L552xx
    $<$<CONFIG:Debug>:DEBUG>
)

# Add include paths
target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE
    ./Core/Inc
    ../Secure_nsclib
    ../Drivers/STM32L5xx_HAL_Driver/Inc
    ../Drivers/CMSIS/Device/ST/STM32L5xx/Include
    ../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy
    ../Drivers/CMSIS/Include
)

# Add sources to executable
target_sources(${CMAKE_PROJECT_NAME} PRIVATE
    ./Core/Src/main.c
    ./Core/Src/stm32l5xx_it.c
    ./Core/Src/stm32l5xx_hal_msp.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_utils.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_exti.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_i2c_ex.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc_ex.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ex.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ramfunc.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gpio.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma_ex.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_exti.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr_ex.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_cortex.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_icache.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc_ex.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_tim_ex.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_adc.c
    ../Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_adc_ex.c
    ./Core/Src/system_stm32l5xx_ns.c
    ./Core/Src/sysmem.c
    ./Core/Src/syscalls.c
    ./Core/Startup/startup_stm32l552xx.s
)

# Link directories setup
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE
)

target_link_libraries(${CMAKE_PROJECT_NAME} Secure_Nsclib)

# Add linked libraries
target_link_libraries(${CMAKE_PROJECT_NAME} 
)

# Validate that STM32CubeMX code is compatible with C standard
if(CMAKE_C_STANDARD LESS 11)
    message(ERROR "Generated code requires C11 or higher")
endif()
